namespace MinigameFramework.Enums
{
    /// <summary>
    /// NPC names.
    /// </summary>
    public enum DisplayableNPC
    {
        Abigail = 0,
        Alex = 1,
        Birdie = 2,
        Bouncer = 3,
        Caroline = 4,
        Clint = 5,
        Demetrius = 6,
        Dwarf = 7,
        Elliot = 8,
        Emily = 9,
        Evelyn = 10,
        Fizz = 11,
        George = 12,
        Gil = 13,
        Governor = 14,
        Grandpa = 15,
        Gunther = 16,
        Gus = 17,
        Haley = 18,
        Harvey = 19,
        Henchman = 20,
        Jas = 21,
        Jodi = 22,
        Kent = 23,
        Krobus = 24,
        Leah = 25,
        Leo = 26,
        Lewis = 27,
        Linus = 28,
        Marlon = 29,
        Marnie = 30,
        Maru = 31,
        Morris = 32,
        Mr_Qi = 33,
        Pam = 34,
        Penny = 35,
        Pierre = 36,
        Professor_Snail = 37,
        Robin = 38,
        Sam = 39,
        Sandy = 40,
        Sebastian = 41,
        Shane = 42,
        Vincent = 43,
        Willy = 44,
        Wizard = 45,
        Bear = 46,
    }
}
