namespace MinigameFramework.Enums
{
    /// <summary>
    /// NPCs with displayable portraits.
    /// 
    /// Alphabetical with some modded options at the bottom...
    /// </summary>
    public enum DisplayableNPC
    {
        // Vanilla Portraits
        Abigail = 0,
        Alex = 1,
        Birdie = 2,
        Bouncer = 3,
        Caroline = 4,
        Clint = 5,
        Demetrius = 6,
        Dwarf = 7,
        Elliot = 8,
        Emily = 9,
        Evelyn = 10,
        Fizz = 11,
        George = 12,
        Gil = 13,
        Governor = 14,
        Grandpa = 15,
        Gunther = 16,
        Gus = 17,
        Haley = 18,
        Harvey = 19,
        Henchman = 20,
        Jas = 21,
        Jodi = 22,
        Kent = 23,
        Krobus = 24,
        Leah = 25,
        Leo = 26,
        Lewis = 27,
        Linus = 28,
        Marlon = 29,
        Marnie = 30,
        Maru = 31,
        Morris = 32,
        Mr_Qi = 33,
        Pam = 34,
        Penny = 35,
        Pierre = 36,
        Professor_Snail = 37,
        Robin = 38,
        Sam = 39,
        Sandy = 40,
        Sebastian = 41,
        Shane = 42,
        Vincent = 43,
        Willy = 44,
        Wizard = 45,
        Bear = 46,

        // Stardew Valley Expanded (SDVE) Portraits
        // https://www.nexusmods.com/stardewvalley/mods/3753
        AlesiaSDVE = 47,
        AndySDVE = 48,
        ApplesSDVE = 49,
        AxelSDVE = 50,
        BrooklynSDVE = 51,
        CamillaSDVE = 52,
        ChloeSDVE = 53,
        ClaireSDVE = 54,
        DustySDVE = 55,
        IsaacSDVE = 56,
        JaceSDVE = 57,
        JaduSDVE = 58,
        JunimosSDVE = 59,
        LanceSDVE = 60,
        MagnusSDVE = 61,
        MartinSDVE = 62,
        MermaidSDVE = 63,
        MorganSDVE = 64,
        OliviaSDVE = 65,
        PeachesSDVE = 66,
        ScarlettSDVE = 67,
        SophiaSDVE = 68,
        SukiSDVE = 69,
        SusanSDVE = 70,
        VictorSDVE = 71,
        ZoeySDVE = 72,

        // Ridgeside Village Portraits
        // https://www.nexusmods.com/stardewvalley/mods/7286
        AcornRV = 73,
        AguarRV = 74,
        AlissaRV = 75,
        AltheaRV = 76,
        AntonRV = 77,
        AriahRV = 78,
        BelindaRV = 79,
        BertRV = 80,
        BlairRV = 81,
        BlissRV = 82,
        BryleRV = 83,
        CarmenRV = 84,
        CorineRV = 85,
        DaiaRV = 86,
        EzekielRV = 87,
        FayeRV = 88,
        FlorRV = 89,
        FreddieRV = 90,
        HelenRV = 91,
        IanRV = 92,
        IreneRV = 93,
        JericRV = 94,
        JioRV = 95,
        JuneRV = 96,
        KeahiRV = 97,
        KennethRV = 98,
        KiarraRV = 99,
        KimpoiRV = 100,
        KiwiRV = 101,
        LennyRV = 102,
        LolaRV = 103,
        LorenzoRV = 104,
        LorraineRV = 105,
        LouieRV = 106,
        MaddieRV = 107,
        MaiveRV = 108,
        MalayaRV = 109,
        NadalineRV = 110,
        NaomiRV = 111,
        OlgaRV = 112,
        PaulaRV = 113,
        PhilipRV = 114,
        PikaRV = 115,
        PipoRV = 116,
        RaeriyalaRV = 117,
        RelicSpiritRV = 118,
        RichardRV = 119,
        SariRV = 120,
        SeanRV = 121,
        ShaniceRV = 122,
        ShiroRV = 123,
        SonnyRV = 124,
        TortsRV = 125,
        TreehouseGirlRV = 126,
        TrinnieRV = 127,
        UndreyaRV = 128,
        YsabelleRV = 129,
        YuumaRV = 130,
        ZacharyRV = 131,
        ZayneRV = 132,

        // East Scarp
        // https://www.nexusmods.com/stardewvalley/mods/5787
        AideenES = 133,
        BeatriceES = 134,
        EloiseES = 135,
        EyvinderES = 136,
        JacobES = 137,
        JosephineES = 138,
        KatarynaES = 139,
        KennedyES = 140,
        LexiES = 141,
        LumaJunimoES = 142,
        OliverES = 143,
        RosaES = 144,
        ToriES = 145,
        VivienneES = 146,
    }
}
